name: Check Branch Sequence

on:
  pull_request:
    types:
      - opened

jobs:
  check-sequence:
    runs-on: ubuntu-latest

    steps:
      - name: Check Sequence
        run: |
          FROM_BRANCH="${{ github.event.pull_request.head.ref }}"
          TO_BRANCH="${{ github.event.pull_request.base.ref }}"

          if [[ "$TO_BRANCH" =~ ^feature.*$ ]] && [ "$FROM_BRANCH" != "develop" ]; then
            echo "Invalid sequence. You can only open a pull request from a 'feature*' branch to 'develop'."
            exit 1
          fi
          if [ "$TO_BRANCH" == "test-mode" ] && [[ ! "$FROM_BRANCH" =~ ^feature.*$ ]]; then
            echo "Invalid sequence. You can only open a pull request from a 'test-mode' branch to a 'feature*' branch."
            exit 1
          fi
          if [ "$TO_BRANCH" == "main" ] && [ "$FROM_BRANCH" != "test-mode" ]; then
            echo "Invalid sequence. You can only open a pull request from 'main' to 'test-mode'."
            exit 1
          fi
