name: Merge test-mode to main

on:
  push:
    branches:
      - 'test-mode'

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR target branch
        id: check_target_branch
        run: echo "CHECK_TARGET_BRANCH=${{ github.ref }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge to Main
        if: ${{ env.CHECK_TARGET_BRANCH == 'refs/heads/test-mode' }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout main
          git merge --allow-unrelated-histories --strategy-option=theirs origin/test-mode
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}