name: Merge develop to test-mode

on:
  push:
    branches:
      - 'develop'

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR target branch
        id: check_target_branch
        run: echo "CHECK_TARGET_BRANCH=${{ github.ref }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge to Test Mode
        if: ${{ env.CHECK_TARGET_BRANCH == 'refs/heads/develop' }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          # Create a PR using the GitHub API
          PR_URL=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "Merge develop into test-mode",
              "head": "develop",
              "base": "test-mode"
            }' \
            "https://api.github.com/repos/${{ github.repository }}/pulls" | jq -r '.html_url')

          PR_NUMBER=$(basename $PR_URL)
          echo "Created PR: $PR_URL with PR_NUMBER: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Automatically merge the PR
        if: ${{ env.CHECK_TARGET_BRANCH == 'refs/heads/develop' }}
        uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          pull-request: ${{ env.PR_NUMBER }}
          dry-run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}