name: Merge to Test and Main

on:
  push:
    branches:
      - '*'

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR target branch
        id: check_target_branch
        run: echo "::set-output name=check_target_branch::${{ github.event.pull_request.base.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge to Test Mode
        if: ${{ steps.check_target_branch.outputs.check_target_branch == 'develop' }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout test-mode
          git merge --allow-unrelated-histories origin/develop
          git push origin test-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge to Main
        if: ${{ steps.check_target_branch.outputs.check_target_branch == 'test-mode' }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout main
          git merge --allow-unrelated-histories origin/test-mode
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
