name: Merge to Test and Main

on:
  pull_request:
    types:
      - closed

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR target branch
        id: check_target_branch
        run: echo "::set-output name=check_target_branch::${{ github.event.pull_request.base.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge to Test Mode
        if: ${{ steps.check_target_branch.outputs.check_target_branch == 'develop' }}
        run: |
          git checkout test-mode
          git pull origin develop
          git push origin test-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge to Main
        if: ${{ steps.check_target_branch.outputs.check_target_branch == 'test-mode' }}
        run: |
          git checkout main
          git pull origin test-mode
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

