name: Merge to Test and Main

on:
  pull_request:
    types:
      - closed

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Check PR target branch
        id: check_target_branch
        run: echo "::set-output name=check_target_branch::${{ github.event.pull_request.base.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge development -> test-mode
        if: ${{ steps.check_target_branch.outputs.check_target_branch == 'develop' }}
        uses: alinasir85/uniswap@main
        with:
          type: now
          from_branch: develop
          target_branch: test-mode
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge test-mode -> main
        if: ${{ steps.check_target_branch.outputs.check_target_branch == 'test-mode' }}
        uses: alinasir85/uniswap@main
        with:
          type: now
          from_branch: test-mode
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
